public enum BlockID
{
    Null = 0,
    GrassBlock = 1,
    DirtBlock = 2,
    RockBlock = 3,
    Tree_Law = 4,
    Tree_Tall = 5,
    Tree_Tall2 = 6,
    Grass = 7,
    Rock = 8,
    Rock_2 = 9,
    Road = 10,
    Ladder = 11,
    Flower_Pink = 12,
    Flower_SkyBlue = 13,
    Flower_White = 14,
    Flower_Yellow = 15,

    Command_Red = 100,
    Command_Green = 101,
    Command_Blue = 102,
    Command_Purple = 103,
    Command_Yellow = 104,
    Command_Cyan = 105,
    Command_White = 106,
    Command_Black = 107,

    Gimmick_Block_Red = 200,
    Gimmick_Block_Green = 201,
    Gimmick_Block_Blue = 202,
    Gimmick_Block_Purple = 203,
    Gimmick_Block_Yellow = 204,
    Gimmick_Block_Cyan = 205,
    Gimmick_Block_White = 206,
    Gimmick_Block_Black = 207,

    Gimmick_ThreeBlock_Red = 300,
    Gimmick_ThreeBlock_Green = 301,
    Gimmick_ThreeBlock_Blue = 302,
    Gimmick_ThreeBlock_Purple = 303,
    Gimmick_ThreeBlock_Yellow = 304,
    Gimmick_ThreeBlock_Cyan = 305,
    Gimmick_ThreeBlock_White = 306,
    Gimmick_ThreeBlock_Black = 307,

    Goal = 99999,
}